modLoader="javafml"
loaderVersion="${loader_range}"
issueTrackerURL="https://github.com/vancevoj/NeoTinkersConstruct/issues"
logoFile="logo.png"
license="MIT"

[[mods]]
    modId="tconstruct"
    version="${version}"
    displayName="Neo Tinkers"
    enumExtensions="META-INF/enumextensions.json"
    authors="Slime Knights, vancevoj"
    description='''
A little of this, a little of that, a lot of tinkering, and a lot of tools. Neo Tinkers is vancevoj's NeoForge 1.21.1 port of Slime Knights' Tinkers' Construct ${mod_version}; it was inspired by their work and nearly all of the design and programming belong to them.
    '''
    displayURL="https://github.com/vancevoj/NeoTinkersConstruct"

[[dependencies.tconstruct]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.tconstruct]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.tconstruct]]
    modId="mantle"
    type="required"
    versionRange="${mantle_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.tconstruct]]
    modId="jei"
    type="optional"
    versionRange="${jei_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.tconstruct]]
    modId="jsonthings"
    type="optional"
    versionRange="${json_things_range}"
    ordering="NONE"
    side="BOTH"
